gravatar:
  default_size: 80
  normal_size: 50
url:
  gravatar: https://secure.gravatar.com/avatar/
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
  avatar:
    accept_types: ["jpg", "jpeg", "gif", "png"]
    file_types: "image/jpeg, image/jpg, image/gif, image/png"
    size: 2
validate:
  max_board_name: 35
  max_board_description: 255
  max_label_content: 35
data:
  confirm: 1
  notconfirm: 0
card:
  name:
    length: 200
  description:
    length: 1000
number:
  zero: 0
  one: 1
  two: 2
validate:
  max_board_name: 40
  max_board_description: 255
  max_list_name: 30
  max_label_content: 30
date:
  form: "%d/%m/%Y"
  hour: "%d/%m/%Y - %H:%M:%S"
checklist:
  name:
    length: 200
background:
  url: https://i.pinimg.com/originals/cb/c2/2c/cbc22ca5a3d7568a742262639a9f6b3f.jpg
noti_action:
  create: 1
  update: 2
attachment:
  name:
    length: 200
  size: 20
  thumb:
    width: 112
    height: 80
